version: "3.7"

services:
  dev-web-converter:
    container_name: dev-web-converter
    build:
      context: .
      dockerfile: config/development/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=web.settings.development
    restart: always
    volumes:
      - ./web:/usr/src/app/web
    command: ["./entrypoint.sh"]
    ports:
      - "127.0.0.15:8080:8000"
